name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.MERGE_BOT_TOKEN }}
          merge-method: squash
          target: minor
          use-github-auto-merge: "true"
